apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-boilerplate
  namespace: frontend
  labels:
    app: fe-boilerplate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fe-boilerplate
  template:
    metadata:
      labels:
        app: fe-boilerplate
    spec:
      containers:
        - name: fe-boilerplate
          image: yepsamii/fe-boilerplate:v1.5
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
